### ISSUE TITLE
test flakes: gcloud crashed (ValueError): not enough values to unpack

### ISSUE THREAD

**Issue by martijnvans** [GoogleCloudPlatform/ops-agent#407]
The full error we get is:

    ERROR: gcloud crashed (ValueError): not enough values to unpack (expected 3, got 1)

Looks like it happens on VM create or delete operations. I'll bump up the verbosity to see if we can glean anything useful from it.

**Comment by martijnvans** [comment]
full stack trace:

        DEBUG: not enough values to unpack (expected 3, got 1)
        Traceback (most recent call last):
          File "/opt/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 987, in Execute
            resources = calliope_command.Run(cli=self, args=args)
          File "/opt/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 809, in Run
            resources = command_instance.Run(args)
          File "/opt/google-cloud-sdk/lib/surface/compute/instances/create.py", line 564, in Run
            return compute_client.MakeRequests(requests)
          File "/opt/google-cloud-sdk/lib/googlecloudsdk/api_lib/compute/client_adapter.py", line 104, in MakeRequests
            timeout=timeout))
          File "/opt/google-cloud-sdk/lib/googlecloudsdk/api_lib/compute/request_helper.py", line 357, in MakeRequests
            timeout=timeout):
          File "/opt/google-cloud-sdk/lib/googlecloudsdk/api_lib/compute/waiters.py", line 483, in WaitForOperations
            batch_url=batch_url)
          File "/opt/google-cloud-sdk/lib/googlecloudsdk/api_lib/compute/batch_helper.py", line 106, in MakeRequests
            batch_request_callback=batch_checker.BatchCheck)
          File "/opt/google-cloud-sdk/lib/third_party/apitools/base/py/batch.py", line 226, in Execute
            batch_http_request.Execute(http)
          File "/opt/google-cloud-sdk/lib/third_party/apitools/base/py/batch.py", line 492, in Execute
            self._Execute(http)
          File "/opt/google-cloud-sdk/lib/third_party/apitools/base/py/batch.py", line 470, in _Execute
            response = self._DeserializeResponse(part.get_payload())
          File "/opt/google-cloud-sdk/lib/third_party/apitools/base/py/batch.py", line 376, in _DeserializeResponse
            _, status, _ = status_line.split(' ', 2)
        ValueError: not enough values to unpack (expected 3, got 1)
        ERROR: gcloud crashed (ValueError): not enough values to unpack (expected 3, got 1)

**Comment by martijnvans** [comment]
They are investigating in bug number 216558719 (google internal bug).

**Comment by martijnvans** [comment]
they have resolved the issue for now, closing.
